### PR TITLE
in progress - working on rule 9

### PR DESCRIPTION
**Pull request by dlebauer**

### CODE REVIEW

**Comment by emhart** [comment]
If this is in progress, should I wait on the merge?

**Comment by dlebauer** [comment]
yes. I made changes in the web interface and didn't know how to create a branch without creating a pull request ...

**Comment by naupaka** [comment]
Hi @dlebauer @emhart once you merge, I have a number of comments on the full draft (which I made on a hard copy) that I'll open as a new PR on the merged version, so as to avoid conflicts...

**Comment by emhart** [comment]
@naupaka Ok, I'll merge now so you can issue your PR.

**Comment by dlebauer** [comment]
good call. Thanks

**Pull request merged**
