### PR TITLE
Added rule 7 on privacy

### PR DESCRIPTION
**Pull request by emhart**
Hi All,

We lost our contributor on the privacy so in the interest of keeping the ball rolling I've written the rule myself.  Please give feedback if you have any, or contribute your own experiences in the challenges of data privacy.

### CODE REVIEW

**Comment by naupaka** [comment]
Look good @emhart! There's a nice post on this at the [Open Science Collaboration blog](http://osc.centerforopenscience.org/2014/01/29/privacy-and-open-data/). They point out that it is also important to consider how to deal with non-explicit but still potentially identifying information related to human subjects (beyond names, SSN, genomic info): demographic variables, outliers and rare values, dates, geographic locations, and participant ID numbers. These are all much more important when dealing with social sciences research and mixed methods data, but perhaps the readership of this article will include Digital Humanities folks as well? So maybe we could have a few more sentences on these types of elements in the data that might need some careful thought before a dataset with human subjects info becomes public.

Just a thought -- not sure how close we are to the word limits already.

**Comment by karawoo** [comment]
I wonder if we need to explain hashing in a little more detail? I think the average researcher wouldn't have more than a general idea of what this means, and without some more concrete description might dismiss it as something they can't do because it's too complicated. I guess this also depends on our audience...

**Comment by naupaka** [comment]
@emhart shall we merge this in so people can start doing pull requests/revisions to the entire manuscript?

**Comment by gvwilson** [comment]
Yes please

**Comment by fmichonneau** [comment]
:+1:

**Pull request merged**
