### PR TITLE
responded to reviewer 3, #128

### PR DESCRIPTION
**Pull request by emhart**
Holding off on merging until I get a bit more feedback from folks.

### CODE REVIEW

**Comment by fmichonneau** [comment]
+1 for me

**Comment by PBarmby** [comment]
I'm fine with the response. Could make a few minor tweaks which might satisfy reviewer:
- in response point out that rule 8 on privacy can be particularly important in biomed contexts
- in manuscript add a few words to this effect

**Comment by naupaka** [comment]
I agree with @emhart but also with @PBarmby's suggestion about pointing out the existing privacy section as relevant to biomed data. 

I also think we should add in a few more mentions of e.g. [NCBI](http://www.ncbi.nlm.nih.gov/)/[EMBL](http://www.ebi.ac.uk/) as repositories for all types of sequencing data. Then I think we could respond to this comment from the review with a few different things, which might be more effective. I think this could go in the permanent identifier section (mention NCBI Accession.Versions vs GI identifiers, [which are being phased out](http://www.ncbi.nlm.nih.gov/news/03-02-2016-phase-out-of-GI-numbers/)) and in the metadata section, where we can mention several tools for formatting and uploading metadata to, e.g., the [NCBI SRA with mothur](http://www.mothur.org/wiki/Make.sra).

**Comment by emhart** [comment]
Thanks all! @naupaka I tried my best to incorporate your comments into the manuscript.  This is a bit out of my realm of expertise so I'd love another set of eyes on it just to make sure it reads correctly. If so I think we can do one last pass and then I'll do the re-submission.

**Comment by naupaka** [comment]
Thanks! If you merge this @emhart I will take one more pass to check for typos and smooth out wording if needed. Probably easier than me trying to add commits on top of your PR.

**Pull request merged**
