### PR TITLE
Preprint edits

### PR DESCRIPTION
**Pull request by emhart**
Addresses issues #114 and #97 along with some minor edits, wrapping up final edits before submission.

### CODE REVIEW

**Comment by naupaka** [comment]
These all look good. Should we also pull out the html comments at this point? Or does it not matter because we will submit the rendered pdf?

**Comment by emhart** [comment]
I think we should clean up the HTML comments, I think most have been addressed when I was looking through the manuscript.

**Comment by naupaka** [comment]
<ping> what still needs to be done to submit? just to take out the html comments?

**Comment by emhart** [comment]
I think so, I seem to recall going through most of the issues. Does it read
like it's ready to submit to you?

**Comment by naupaka** [comment]
I can check through it tonight and remove any last comments, etc. Maybe merge this PR now so everything stays organized?

**Pull request merged**
